import type { MenuItem } from "#/menu";

export const menuList: MenuItem[] = [{
    id: 1,
    type: 0,
    path: "/dashboard",
    name: "Dashboard",
    title: "Dashboard",
    icon: "dashboard",
    visible: "1",
    sort: 1,
    children: [{
        id: 11,
        type: 1,
        path: "/console",
        name: "Console",
        title: "主控台",
        sort: 1,
        isCache: "0",
        visible: "1",
        component: "/dashboard/console",
        children: [],
    }, {
        id: 12,
        type: 1,
        path: "/workbench",
        name: "Workbench",
        title: "工作台",
        isCache: "0",
        visible: "1",
        sort: 2,
        component: "/dashboard/workbench",
        children: [],
    }],
}, {
    id: 2,
    type: 0,
    path: "/comps",
    name: "Comps",
    title: "组件示例",
    icon: "dashboard",
    visible: "1",
    sort: 1,
    children: [{
        id: 21,
        type: 1,
        path: "/icons",
        name: "Icons",
        title: "图标",
        sort: 1,
        isCache: "0",
        visible: "1",
        component: "/comps/icons",
        children: [],
    }],
}, {
    id: 3,
    type: 0,
    path: "/error",
    name: "Error",
    title: "异常页面",
    icon: "question",
    visible: "1",
    sort: 2,
    children: [{
        id: 31,
        type: 1,
        path: "404",
        name: "404",
        title: "404",
        icon: "404",
        isCache: "0",
        visible: "1",
        sort: 2,
        component: "/error/404",
        children: [],
    }, {
        id: 32,
        type: 1,
        path: "403",
        name: "403",
        title: "403",
        isCache: "0",
        visible: "1",
        sort: 2,
        component: "/error/403",
        children: [],
    }],
}, {
    id: 11,
    type: 1,
    path: "/about",
    name: "About",
    title: "关于",
    visible: "1",
    icon: "EleNotebook",
    sort: 3,
    component: "/about",
    children: [],
}];

export function getMenus() {
    return new Promise<MenuItem[]>(resolve => {
        resolve(menuList);
    });
}